services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_BASE_PATH=${VITE_API_BASE_PATH}
    container_name: cnd-web
    ports:
      - "4173:4173"
    restart: unless-stopped

